### ISSUE TITLE
[Bug] docker container cannot find yarn

### ISSUE THREAD

**Issue by cowboyd** [MarvinJWendt/run-node-formatter#14]
Trying to use this action on the following repo, which has a `lint` script. but th getting the `"Yan: command not found" error. `https://github.com/bigtestjs/server/pull/8/checks?check_run_id=291815274#step:3:20

Seems like I might be missing something?

**Comment by MarvinJWendt** [comment]
Hi @cowboyd, it should work now.
If it doesn't, please don't hesitate to ping me here.

Thanks for reporting 😄 

PS: Remember to update to version 1.5.1 :)
